// 定义奖励文本对象，用于将奖励类型映射到中文描述
export const REWARD_MAP = {
  message_cloudmusic: '分享音符',
  outfit_prop_saxophone: '萨克斯试用魔法',
  outfit_prop_violin: '小提琴试用魔法*',
  outfit_prop_triumphhandpan: '凯旋手碟试用魔法',
  outfit_prop_rhythmguitar: '白吉它试用魔法',
  outfit_prop_fledglingharp: '雏鸟之琴试用魔法',
  swing: '秋千',
  outfit_prop_cloudmusictable: '古典音乐桌椅试用魔法',
  heart: '爱心',
  candles: '蜡烛',
  bonfire: '篝火',
  glow: '璀璨之星',
  gravity: '漂浮',
  table: '畅谈长桌',
  repellant_krill: '冥龙克星',
  resize_potion: '体型重塑',
  CharSkyKid_Hair_WerewolfWitch: '兜帽女巫发型',
  energy_potion: '光能药剂',
  CharSkyKid_Wing_WerewolfWitch: '红底女巫斗篷',
  message_boat: '传信纸船',
  activitycenter_netease_werewolf_m2: '礼物小心心',
  activitycenter_netease_werewolf_m3: '联动表情：关心',
  trail_rainbow: '彩虹尾迹',
  activitycenter_netease_werewolf_m5: '联动场景：云野(21天)',
  rainbow: '绚丽彩虹',
  activitycenter_netease_werewolf_m7: '联动光崽麦克风',
  CharSkyKid_Mask_Werewolf: '头狼面具',
  fireworks: '浪漫烟花',
  birthdaycake_medium: '生日蛋糕',
  birthdaycake_large: '生日庆典大蛋糕',
  outfit_prop_birthdayoreo: '周年庆抱枕魔法',
  season_candle: '季节蜡烛',
  recording_candle: '留影蜡烛',
  sharedspace_candle: '共享空间',
  shrink: '返老还童',
  tiny: '小不点',
  grow: '长大成人',
  huge: '大只佬',
  crab_rock_trick: '螃蟹恶作剧',
  currency_trick: '糖果恶作剧',
  random_dice: '蟹蟹的士',
  custom_dice: '遥鲲飞机',
  candle_trick: '蜡烛恶作剧',
  outfit_hair_witchhair: '女巫长发试用魔法',
  outfit_wing_witheredcape: '枯叶斗篷试用魔法',
  outfit_prop_mischieftable: '枯木桌椅试用魔法',
  outfit_feet_goth: '哥特长靴试用魔法',
  outfit_horn_pumpkincrab: '螃蟹南瓜头饰试用魔法',
  outfit_mask_crabula: '吸蟹伯爵面具礼包试用魔法',
  outfit_wing_crabula: '吸蟹伯爵斗篷礼包试用魔法',
  outfit_body_goth: '哥特螃蟹长袍试用魔法',
  outfit_wing_cobweb: '蛛丝斗篷礼包试用魔法',
  outfit_wing_catcape: '皮皮猫装扮礼包试用魔法',
  outfit_prop_mischiefpumpkin: '冥龙南瓜礼包试用魔法',
  outfit_hair_cathair: '猫耳发型试用魔法',
  outfit_prop_mischiefcat: '皮皮猫礼包试用魔法',
  outfit_prop_mischiefbroom: '恶作剧飞行扫帚礼包试用魔法',
  outfit_hair_spiderhair: '蛛网朋克礼包试用魔法',
  outfit_body_witchbody: '疯女巫长裙礼包试用魔法',
  outfit_horn_witheredhorn: '巫树犄角礼包试用魔法',
  outfit_wing_bat: '鬼蝠斗篷试用魔法',
  outfit_hair_pumpkin: '南瓜帽试用魔法',
  outfit_wing_webcape: '蛛网斗篷礼包试用魔法',
  outfit_hair_witchhat: '女巫帽礼包试用魔法',
  ticket: '捣蛋挖宝次数',
  energy: '元气满满',
  kizuna_ai_dumpling: '中国绊爱饺子魔法',
  outfit_prop_kizuna_ai_tv: '中国绊爱大铁头礼包试用魔法',
  outfit_horn_kizuna: '中国绊爱发饰试用魔法',
  outfit_wing_kizuna: '中国绊爱斗篷魔法',
  outfit_hair_kizuna: '中国绊爱发型魔法',
  prestige: '升华蜡烛',
  CharSkyKid_Horn_AP12SideFeather_Red: '红色单边双羽发饰',
  CharSkyKid_Prop_BalloonRed: '红色气球',
  CharSkyKid_Neck_AP07BowTie_02: '红色领结',
  CharSkyKid_Horn_FlowerPoppy_02: '小红花发饰',
  breath_potion: '呼吸药剂',
  outfit_hair_naturewater: '海蓝波浪发型试用魔法',
  trail_aquamarine: '海蓝尾迹',
  trail_pink: '粉红尾迹',
  trail_red: '红色尾迹',
  trail_orange: '橙色尾迹',
  trail_yellow: '黄色尾迹',
  trail_green: '绿色尾迹',
  trail_cyan: '青色尾迹',
  trail_blue: '淡蓝尾迹',
  trail_purple: '紫色尾迹',
  season_candles: '新季节蜡烛',
  outfit_prop_marshmallow: '篝火点心礼包试用魔法',
  beachball: '沙滩弹球',
  outfit_prop_mantafloat: '遥鲲泳圈试用魔法',
  outfit_prop_surfboard: '夏日冲浪礼包试用魔法',
  flair_flower: '炫彩步尘',
}

export interface RewardMap {
  message_cloudmusic: '分享音符'
  outfit_prop_saxophone: '萨克斯试用魔法'
  outfit_prop_violin: '小提琴试用魔法*'
  outfit_prop_triumphhandpan: '凯旋手碟试用魔法'
  outfit_prop_rhythmguitar: '白吉它试用魔法'
  outfit_prop_fledglingharp: '雏鸟之琴试用魔法'
  swing: '秋千'
  outfit_prop_cloudmusictable: '古典音乐桌椅试用魔法'
  heart: '爱心'
  candles: '蜡烛'
  bonfire: '篝火'
  glow: '璀璨之星'
  gravity: '漂浮'
  table: '畅谈长桌'
  repellant_krill: '冥龙克星'
  resize_potion: '体型重塑'
  CharSkyKid_Hair_WerewolfWitch: '兜帽女巫发型'
  energy_potion: '光能药剂'
  CharSkyKid_Wing_WerewolfWitch: '红底女巫斗篷'
  message_boat: '传信纸船'
  activitycenter_netease_werewolf_m2: '礼物小心心'
  activitycenter_netease_werewolf_m3: '联动表情：关心'
  trail_rainbow: '彩虹尾迹'
  activitycenter_netease_werewolf_m5: '联动场景：云野(21天)'
  rainbow: '绚丽彩虹'
  activitycenter_netease_werewolf_m7: '联动光崽麦克风'
  CharSkyKid_Mask_Werewolf: '头狼面具'
  fireworks: '浪漫烟花'
  birthdaycake_medium: '生日蛋糕'
  birthdaycake_large: '生日庆典大蛋糕'
  outfit_prop_birthdayoreo: '周年庆抱枕魔法'
  season_candle: '季节蜡烛'
  recording_candle: '留影蜡烛'
  sharedspace_candle: '共享空间'
  shrink: '返老还童'
  tiny: '小不点'
  grow: '长大成人'
  huge: '大只佬'
  crab_rock_trick: '螃蟹恶作剧'
  currency_trick: '糖果恶作剧'
  random_dice: '蟹蟹的士'
  custom_dice: '遥鲲飞机'
  candle_trick: '蜡烛恶作剧'
  outfit_hair_witchhair: '女巫长发试用魔法'
  outfit_wing_witheredcape: '枯叶斗篷试用魔法'
  outfit_prop_mischieftable: '枯木桌椅试用魔法'
  outfit_feet_goth: '哥特长靴试用魔法'
  outfit_horn_pumpkincrab: '螃蟹南瓜头饰试用魔法'
  outfit_mask_crabula: '吸蟹伯爵面具礼包试用魔法'
  outfit_wing_crabula: '吸蟹伯爵斗篷礼包试用魔法'
  outfit_body_goth: '哥特螃蟹长袍试用魔法'
  outfit_wing_cobweb: '蛛丝斗篷礼包试用魔法'
  outfit_wing_catcape: '皮皮猫装扮礼包试用魔法'
  outfit_prop_mischiefpumpkin: '冥龙南瓜礼包试用魔法'
  outfit_hair_cathair: '猫耳发型试用魔法'
  outfit_prop_mischiefcat: '皮皮猫礼包试用魔法'
  outfit_prop_mischiefbroom: '恶作剧飞行扫帚礼包试用魔法'
  outfit_hair_spiderhair: '蛛网朋克礼包试用魔法'
  outfit_body_witchbody: '疯女巫长裙礼包试用魔法'
  outfit_horn_witheredhorn: '巫树犄角礼包试用魔法'
  outfit_wing_bat: '鬼蝠斗篷试用魔法'
  outfit_hair_pumpkin: '南瓜帽试用魔法'
  outfit_wing_webcape: '蛛网斗篷礼包试用魔法'
  outfit_hair_witchhat: '女巫帽礼包试用魔法'
  ticket: '捣蛋挖宝次数'
  energy: '元气满满'
  kizuna_ai_dumpling: '中国绊爱饺子魔法'
  outfit_prop_kizuna_ai_tv: '中国绊爱大铁头礼包试用魔法'
  outfit_horn_kizuna: '中国绊爱发饰试用魔法'
  outfit_wing_kizuna: '中国绊爱斗篷魔法'
  outfit_hair_kizuna: '中国绊爱发型魔法'
  prestige: '升华蜡烛'
  CharSkyKid_Horn_AP12SideFeather_Red: '红色单边双羽发饰'
  CharSkyKid_Prop_BalloonRed: '红色气球'
  CharSkyKid_Neck_AP07BowTie_02: '红色领结'
  CharSkyKid_Horn_FlowerPoppy_02: '小红花发饰'
  breath_potion: '呼吸药剂'
  outfit_hair_naturewater: '海蓝波浪发型试用魔法'
  trail_aquamarine: '海蓝尾迹'
  trail_pink: '粉红尾迹'
  trail_red: '红色尾迹'
  trail_orange: '橙色尾迹'
  trail_yellow: '黄色尾迹'
  trail_green: '绿色尾迹'
  trail_cyan: '青色尾迹'
  trail_blue: '淡蓝尾迹'
  trail_purple: '紫色尾迹'
  season_candles: '新季节蜡烛'
  outfit_prop_marshmallow: '篝火点心礼包试用魔法'
  beachball: '沙滩弹球'
  outfit_prop_mantafloat: '遥鲲泳圈试用魔法'
  outfit_prop_surfboard: '夏日冲浪礼包试用魔法'
  flair_flower: '炫彩步尘'
}
