/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    VanLoading: (typeof import('vant/es'))['Loading']
    VanOverlay: (typeof import('vant/es'))['Overlay']
    VanRadio: (typeof import('vant/es'))['Radio']
    VanRadioGroup: (typeof import('vant/es'))['RadioGroup']
    VanShareSheet: (typeof import('vant/es'))['ShareSheet']
    VanSwipe: (typeof import('vant/es'))['Swipe']
    VanSwipeItem: (typeof import('vant/es'))['SwipeItem']
  }
}
